config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id             :integer          not null, primary key
#  band           :string           not null
#  studio_or_live :string           not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Album < ActiveRecord::Base
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ActiveRecord::Base
end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id               :integer          not null, primary key
#  album            :string           not null
#  bonus_or_regular :string           not null
#  lyrics           :text             not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Track < ActiveRecord::Base
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base

  after_initialize :ensure_session_token

  validates :password, length: { minimum: 6, allow_nil: true }

  #should probably have some other validations
  attr_reader :password


  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  private

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :logged_in?

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout_user!(user)
    user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    true unless current_user.nil?
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_credentials(params[:user][:email],
                                    params[:user][:password])
    if user.nil?
      flash.now[:errors] = ["ya done goofed"]
      render :new
    else
      login_user!(user)
      redirect_to user_url(user)
    end
  end

  def new
    render :new
  end

  def destroy
    logout_user!(current_user)
    redirect_to new_user_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    if @user.save
      login_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new
    render :new
  end

  def show
    # @user = User.find_by_id(params[:id])
    @user = current_user
    render :show
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
  <!DOCTYPE html>
<html>

<% if current_user %>
  <%= button_to "logout", session_url, method: "delete" %>
  <%= "you are logged in as #{current_user.email}" %>
<% end %>

<head>
  <title>Music</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Create User</h1>

<% if flash[:errors] %>
  <ul>
    <% flash[:errors].each do |error| %>
  	  <li><%= error %></li>
  	<% end %>
	</ul>
<% end %>

<form action="<%= users_url %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="e_mail">email</label>
  <input
    type="text"
    name="user[email]"
    id="e_mail"
    value="<%= @user.email %>">
  <br>

  <label for="pass_word">password</label>
  <input
    type="password"
    name=user[password]
    id="pass_word"
    value="<%= @user.password %>">
  <br>

  <input type="submit">

app/views/users/show.html.erb
<h1>Show user</h1>

<%= @user.email %>